name: Compile LaTeX documents

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed .tex files
        id: changed-tex
        uses: tj-actions/changed-files@v44
        with:
          files: '**/*.tex'

      - name: Compile LaTeX documents
        if: steps.changed-tex.outputs.any_changed == 'true'
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ steps.changed-tex.outputs.all_changed_files }}
          # Se usa pdflatex por defecto, no es necesario especificarlo

      - name: Commit PDFs
        if: steps.changed-tex.outputs.any_changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f *.pdf
          git commit -m "chore: se agregan los PDFs compilados ♻️" || echo "No changes to commit"
          git push
